import { z } from "zod";

export const Language = {
  /**
   * @deprecated This language is superseded by 'en-US'
   */
  en: "en",
  /**
   * @deprecated This language is superseded by 'de-DE'
   */
  de: "de",
  "sq-AL": "sq-AL",
  "hy-AM": "hy-AM",
  "az-AZ": "az-AZ",
  "eu-ES": "eu-ES",
  "be-BY": "be-BY",
  "bs-BA": "bs-BA",
  "br-FR": "br-FR",
  "bg-BG": "bg-BG",
  "ca-ES": "ca-ES",
  "hr-HR": "hr-HR",
  "cs-CZ": "cs-CZ",
  "da-DK": "da-DK",
  "nl-NL": "nl-NL",
  "en-GB": "en-GB",
  "en-US": "en-US",
  "en-IE": "en-IE",
  "et-EE": "et-EE",
  "fo-FO": "fo-FO",
  "fi-FI": "fi-FI",
  "fr-FR": "fr-FR",
  "fy-NL": "fy-NL",
  "gl-ES": "gl-ES",
  "de-DE": "de-DE",
  "de-AT": "de-AT",
  "de-CH": "de-CH",
  "el-GR": "el-GR",
  "el-CY": "el-CY",
  "hu-HU": "hu-HU",
  "is-IS": "is-IS",
  "ga-IE": "ga-IE",
  "it-IT": "it-IT",
  "it-CH": "it-CH",
  "lv-LV": "lv-LV",
  "lt-LT": "lt-LT",
  "lb-LU": "lb-LU",
  "mk-MK": "mk-MK",
  "mt-MT": "mt-MT",
  "nb-NO": "nb-NO",
  "nn-NO": "nn-NO",
  "pl-PL": "pl-PL",
  "pt-PT": "pt-PT",
  "ro-RO": "ro-RO",
  "ro-MD": "ro-MD",
  "rm-CH": "rm-CH",
  "ru-RU": "ru-RU",
  "gd-GB": "gd-GB",
  "sr-Cyr": "sr-Cyr",
  "sr-Lat": "sr-Lat",
  "sr-Cyrl-RS": "sr-Cyrl-RS",
  "sr-Latn-RS": "sr-Latn-RS",
  "sk-SK": "sk-SK",
  "sl-SI": "sl-SI",
  "es-ES": "es-ES",
  "sv-SE": "sv-SE",
  "sv-FI": "sv-FI",
  "tr-TR": "tr-TR",
  "uk-UA": "uk-UA",
  "cy-GB": "cy-GB",
  "zh-Hans-CN": "zh-Hans-CN",
  "zh-Hant-TW": "zh-Hant-TW",
  "bn-BD": "bn-BD",
} as const;
export const LanguageEnum = z.enum(Language);
export type LanguageType = z.infer<typeof LanguageEnum>;
