packages:
  - apps/*/*
  - apps/*
  - packages/*

injectWorkspacePackages: true

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - core-js
  - cypress
  - esbuild
  - fsevents
  - highlight.js
  - msw
  - sharp
  - unrs-resolver
