packages:
  - apps/*
  - packages/*
  - docs

allowBuilds:
  '@nestjs/core': true
  '@scarf/scarf': true
  '@swc/core': true
  core-js: true
  esbuild: true
  highlight.js: true
  mongodb-memory-server: true
  msw: true
  sharp: true
  unrs-resolver: true
  vue-demi: true

injectWorkspacePackages: true

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@scarf/scarf"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - better-sqlite3
  - core-js
  - esbuild
  - fsevents
  - highlight.js
  - mongodb-memory-server
  - msw
  - sharp
  - unrs-resolver
  - vue-demi
