packages:
  - apps/*
  - packages/*
  - docs

injectWorkspacePackages: true

allowBuilds:
  "@nestjs/core": true
  "@scarf/scarf": true
  "@swc/core": true
  "@tailwindcss/oxide": true
  better-sqlite3: true
  core-js: true
  esbuild: true
  fsevents: true
  highlight.js: true
  mongodb-memory-server: true
  msw: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
