packages:
  - apps/*/*
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@tailwindcss/oxide'
  - core-js
  - cypress
  - esbuild
  - msw
  - sharp
  - unrs-resolver
